### ISSUE TITLE
Support specifying email domain other than hostname by automatically resolving MX record

### ISSUE THREAD

**Issue by Gowee** [cole/aiosmtplib#118]
Hello.

Sometimes it may be desirable to send emails directly to remote mail servers instead of `localhost`. In my case, I want to [push books](https://www.amazon.com/gp/sendtokindle) to Kindle devices by sending emails to `@kindle.com`.

After roughly looking through the source code, I suppose there is no way so far to specify an email domain (e.g. `kindle.com` in my case) instead of `hostname`. I think it would be great if this can be supported by aiosmtplib as it is such a common use scenario. It does take much effort to figure out how to properly resolve and maintain cache/TTL of MX records with asyncio. 

Thanks for the project.

**Comment by cole** [comment]
It sounds like you just need to send an email with the to address as `email@kindle.com`? If so that's not related to the hostname argument.

**Comment by Gowee** [comment]
@cole I'm not sure whether I get the point.

But I am sending directly to the SMTP server pointed by the MX record of `kindle.com` (i.e. `etail-smtp-in.amazon.com.` for now). There is no intermediate mail server because I am not using third party email service (e.g. GMail, MailGrid) or setting up a local mail server (e.g. Sendmail daemon) for further forwading.

For example, 
```python
...
aiosmtplib.send(message, ..., recipients="email@kindle.com", hostname=resolve_mx("Kindle.com"))
```

**Comment by cole** [comment]
Does that work with smtplib?

**Comment by Gowee** [comment]
No. smtplib also do not have this feature yet.

**Comment by cole** [comment]
Ah, I think I misunderstood, so the only missing piece here is `resolve_mx`, right? If you manually input `retail-smtp-in.amazon.com`, it should work with both smtplib and aiosmtplib.

I don't think that's something I want to implement in aiosmtplib. Reasoning as follows:

1. This is kind of unrelated to core functionality and can be just as easily implemented outside of aiosmtplib.
2. Asyncio DNS isn't easy, currently we still have a blocking lookup for the hostname given. I don't know how to asynchronously resolve MX records.
3. It's pretty error prone due to abuse — for example with the example MX server you gave, SMTP access is (reasonably) blocked from dynamic IPs to prevent spam. Most people should be using a dedicated SMTP server they have an account for, as that will make delivery more likely.
