### ISSUE TITLE
regarding the concurrency benenchmark

### ISSUE THREAD

**Issue by zh0uquan** [cole/aiosmtplib#32]
@cole Hello cole, thanks for the good library, learned a lot from this cool asyncio library.

 As you said in the [parallel execution](https://aiosmtplib.readthedocs.io/en/latest/overview.html#parallel-execution), we can't gain a lot from asynchronous communication since SMTP is sequential protocol, thus even with async, we can only send email one by one, thus we can't solve I/O bound issue except creating a new SMTP client. 
so this means we either have lots of emails to send to one smtp server, or emails belongs to different smtp server, thus we gain benefits? and have you done some benchmark some comparing to sync smtp client in threads?

**Comment by cole** [comment]
@zh0uquan glad it's been helpful and thanks for your contribution!

aiosmtplib came about because I wanted to send email from an application that was already async, without having to block or start another thread/process. I haven't done any benchmarks vs using threads — I'd expect performance would be pretty similar.

**Comment by zh0uquan** [comment]
ah, ok. Thanks for the Information. Sad that SMTP server keep states..
